// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/resources/proto/test.proto

package com.samn;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FooOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string sattr = 1;
    /**
     * <code>required string sattr = 1;</code>
     */
    boolean hasSattr();
    /**
     * <code>required string sattr = 1;</code>
     */
    java.lang.String getSattr();
    /**
     * <code>required string sattr = 1;</code>
     */
    com.google.protobuf.ByteString
        getSattrBytes();

    // optional uint64 iattr = 2;
    /**
     * <code>optional uint64 iattr = 2;</code>
     */
    boolean hasIattr();
    /**
     * <code>optional uint64 iattr = 2;</code>
     */
    long getIattr();

    // repeated uint32 iiattr = 3;
    /**
     * <code>repeated uint32 iiattr = 3;</code>
     */
    java.util.List<java.lang.Integer> getIiattrList();
    /**
     * <code>repeated uint32 iiattr = 3;</code>
     */
    int getIiattrCount();
    /**
     * <code>repeated uint32 iiattr = 3;</code>
     */
    int getIiattr(int index);

    // optional .Test.Foo.Bar bar = 4;
    /**
     * <code>optional .Test.Foo.Bar bar = 4;</code>
     */
    boolean hasBar();
    /**
     * <code>optional .Test.Foo.Bar bar = 4;</code>
     */
    com.samn.Test.Foo.Bar getBar();
    /**
     * <code>optional .Test.Foo.Bar bar = 4;</code>
     */
    com.samn.Test.Foo.BarOrBuilder getBarOrBuilder();
  }
  /**
   * Protobuf type {@code Test.Foo}
   */
  public static final class Foo extends
      com.google.protobuf.GeneratedMessage
      implements FooOrBuilder {
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Foo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Foo defaultInstance;
    public static Foo getDefaultInstance() {
      return defaultInstance;
    }

    public Foo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Foo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sattr_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              iattr_ = input.readUInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                iiattr_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              iiattr_.add(input.readUInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                iiattr_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                iiattr_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              com.samn.Test.Foo.Bar.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = bar_.toBuilder();
              }
              bar_ = input.readMessage(com.samn.Test.Foo.Bar.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bar_);
                bar_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          iiattr_ = java.util.Collections.unmodifiableList(iiattr_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.samn.Test.internal_static_Test_Foo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.samn.Test.internal_static_Test_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.samn.Test.Foo.class, com.samn.Test.Foo.Builder.class);
    }

    public static com.google.protobuf.Parser<Foo> PARSER =
        new com.google.protobuf.AbstractParser<Foo>() {
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    public interface BarOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated .Test.Foo.Bar.Baz bazs = 1;
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      java.util.List<com.samn.Test.Foo.Bar.Baz> 
          getBazsList();
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      com.samn.Test.Foo.Bar.Baz getBazs(int index);
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      int getBazsCount();
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      java.util.List<? extends com.samn.Test.Foo.Bar.BazOrBuilder> 
          getBazsOrBuilderList();
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      com.samn.Test.Foo.Bar.BazOrBuilder getBazsOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code Test.Foo.Bar}
     */
    public static final class Bar extends
        com.google.protobuf.GeneratedMessage
        implements BarOrBuilder {
      // Use Bar.newBuilder() to construct.
      private Bar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Bar(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Bar defaultInstance;
      public static Bar getDefaultInstance() {
        return defaultInstance;
      }

      public Bar getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Bar(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  bazs_ = new java.util.ArrayList<com.samn.Test.Foo.Bar.Baz>();
                  mutable_bitField0_ |= 0x00000001;
                }
                bazs_.add(input.readMessage(com.samn.Test.Foo.Bar.Baz.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            bazs_ = java.util.Collections.unmodifiableList(bazs_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.samn.Test.internal_static_Test_Foo_Bar_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.samn.Test.internal_static_Test_Foo_Bar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.samn.Test.Foo.Bar.class, com.samn.Test.Foo.Bar.Builder.class);
      }

      public static com.google.protobuf.Parser<Bar> PARSER =
          new com.google.protobuf.AbstractParser<Bar>() {
        public Bar parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bar(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Bar> getParserForType() {
        return PARSER;
      }

      public interface BazOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

        // optional string baz = 1;
        /**
         * <code>optional string baz = 1;</code>
         */
        boolean hasBaz();
        /**
         * <code>optional string baz = 1;</code>
         */
        java.lang.String getBaz();
        /**
         * <code>optional string baz = 1;</code>
         */
        com.google.protobuf.ByteString
            getBazBytes();
      }
      /**
       * Protobuf type {@code Test.Foo.Bar.Baz}
       */
      public static final class Baz extends
          com.google.protobuf.GeneratedMessage
          implements BazOrBuilder {
        // Use Baz.newBuilder() to construct.
        private Baz(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
          super(builder);
          this.unknownFields = builder.getUnknownFields();
        }
        private Baz(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final Baz defaultInstance;
        public static Baz getDefaultInstance() {
          return defaultInstance;
        }

        public Baz getDefaultInstanceForType() {
          return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
          return this.unknownFields;
        }
        private Baz(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          initFields();
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  baz_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.samn.Test.internal_static_Test_Foo_Bar_Baz_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.samn.Test.internal_static_Test_Foo_Bar_Baz_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.samn.Test.Foo.Bar.Baz.class, com.samn.Test.Foo.Bar.Baz.Builder.class);
        }

        public static com.google.protobuf.Parser<Baz> PARSER =
            new com.google.protobuf.AbstractParser<Baz>() {
          public Baz parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Baz(input, extensionRegistry);
          }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Baz> getParserForType() {
          return PARSER;
        }

        private int bitField0_;
        // optional string baz = 1;
        public static final int BAZ_FIELD_NUMBER = 1;
        private java.lang.Object baz_;
        /**
         * <code>optional string baz = 1;</code>
         */
        public boolean hasBaz() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string baz = 1;</code>
         */
        public java.lang.String getBaz() {
          java.lang.Object ref = baz_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              baz_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string baz = 1;</code>
         */
        public com.google.protobuf.ByteString
            getBazBytes() {
          java.lang.Object ref = baz_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            baz_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private void initFields() {
          baz_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;

          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getBazBytes());
          }
          getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getBazBytes());
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }

        public static com.samn.Test.Foo.Bar.Baz parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }
        public static com.samn.Test.Foo.Bar.Baz parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input);
        }
        public static com.samn.Test.Foo.Bar.Baz parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static com.samn.Test.Foo.Bar.Baz parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.samn.Test.Foo.Bar.Baz prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code Test.Foo.Bar.Baz}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements com.samn.Test.Foo.Bar.BazOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.samn.Test.internal_static_Test_Foo_Bar_Baz_descriptor;
          }

          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.samn.Test.internal_static_Test_Foo_Bar_Baz_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.samn.Test.Foo.Bar.Baz.class, com.samn.Test.Foo.Bar.Baz.Builder.class);
          }

          // Construct using com.samn.Test.Foo.Bar.Baz.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }

          public Builder clear() {
            super.clear();
            baz_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
          }

          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }

          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.samn.Test.internal_static_Test_Foo_Bar_Baz_descriptor;
          }

          public com.samn.Test.Foo.Bar.Baz getDefaultInstanceForType() {
            return com.samn.Test.Foo.Bar.Baz.getDefaultInstance();
          }

          public com.samn.Test.Foo.Bar.Baz build() {
            com.samn.Test.Foo.Bar.Baz result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public com.samn.Test.Foo.Bar.Baz buildPartial() {
            com.samn.Test.Foo.Bar.Baz result = new com.samn.Test.Foo.Bar.Baz(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.baz_ = baz_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }

          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.samn.Test.Foo.Bar.Baz) {
              return mergeFrom((com.samn.Test.Foo.Bar.Baz)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(com.samn.Test.Foo.Bar.Baz other) {
            if (other == com.samn.Test.Foo.Bar.Baz.getDefaultInstance()) return this;
            if (other.hasBaz()) {
              bitField0_ |= 0x00000001;
              baz_ = other.baz_;
              onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }

          public final boolean isInitialized() {
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.samn.Test.Foo.Bar.Baz parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (com.samn.Test.Foo.Bar.Baz) e.getUnfinishedMessage();
              throw e;
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          // optional string baz = 1;
          private java.lang.Object baz_ = "";
          /**
           * <code>optional string baz = 1;</code>
           */
          public boolean hasBaz() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>optional string baz = 1;</code>
           */
          public java.lang.String getBaz() {
            java.lang.Object ref = baz_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              baz_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string baz = 1;</code>
           */
          public com.google.protobuf.ByteString
              getBazBytes() {
            java.lang.Object ref = baz_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              baz_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string baz = 1;</code>
           */
          public Builder setBaz(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            baz_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string baz = 1;</code>
           */
          public Builder clearBaz() {
            bitField0_ = (bitField0_ & ~0x00000001);
            baz_ = getDefaultInstance().getBaz();
            onChanged();
            return this;
          }
          /**
           * <code>optional string baz = 1;</code>
           */
          public Builder setBazBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            baz_ = value;
            onChanged();
            return this;
          }

          // @@protoc_insertion_point(builder_scope:Test.Foo.Bar.Baz)
        }

        static {
          defaultInstance = new Baz(true);
          defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:Test.Foo.Bar.Baz)
      }

      // repeated .Test.Foo.Bar.Baz bazs = 1;
      public static final int BAZS_FIELD_NUMBER = 1;
      private java.util.List<com.samn.Test.Foo.Bar.Baz> bazs_;
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      public java.util.List<com.samn.Test.Foo.Bar.Baz> getBazsList() {
        return bazs_;
      }
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      public java.util.List<? extends com.samn.Test.Foo.Bar.BazOrBuilder> 
          getBazsOrBuilderList() {
        return bazs_;
      }
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      public int getBazsCount() {
        return bazs_.size();
      }
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      public com.samn.Test.Foo.Bar.Baz getBazs(int index) {
        return bazs_.get(index);
      }
      /**
       * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
       */
      public com.samn.Test.Foo.Bar.BazOrBuilder getBazsOrBuilder(
          int index) {
        return bazs_.get(index);
      }

      private void initFields() {
        bazs_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < bazs_.size(); i++) {
          output.writeMessage(1, bazs_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < bazs_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, bazs_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.samn.Test.Foo.Bar parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.samn.Test.Foo.Bar parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.samn.Test.Foo.Bar parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.samn.Test.Foo.Bar parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.samn.Test.Foo.Bar parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.samn.Test.Foo.Bar parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.samn.Test.Foo.Bar parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.samn.Test.Foo.Bar parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.samn.Test.Foo.Bar parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.samn.Test.Foo.Bar parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.samn.Test.Foo.Bar prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Test.Foo.Bar}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.samn.Test.Foo.BarOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.samn.Test.internal_static_Test_Foo_Bar_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.samn.Test.internal_static_Test_Foo_Bar_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.samn.Test.Foo.Bar.class, com.samn.Test.Foo.Bar.Builder.class);
        }

        // Construct using com.samn.Test.Foo.Bar.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getBazsFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (bazsBuilder_ == null) {
            bazs_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            bazsBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.samn.Test.internal_static_Test_Foo_Bar_descriptor;
        }

        public com.samn.Test.Foo.Bar getDefaultInstanceForType() {
          return com.samn.Test.Foo.Bar.getDefaultInstance();
        }

        public com.samn.Test.Foo.Bar build() {
          com.samn.Test.Foo.Bar result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.samn.Test.Foo.Bar buildPartial() {
          com.samn.Test.Foo.Bar result = new com.samn.Test.Foo.Bar(this);
          int from_bitField0_ = bitField0_;
          if (bazsBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              bazs_ = java.util.Collections.unmodifiableList(bazs_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.bazs_ = bazs_;
          } else {
            result.bazs_ = bazsBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.samn.Test.Foo.Bar) {
            return mergeFrom((com.samn.Test.Foo.Bar)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.samn.Test.Foo.Bar other) {
          if (other == com.samn.Test.Foo.Bar.getDefaultInstance()) return this;
          if (bazsBuilder_ == null) {
            if (!other.bazs_.isEmpty()) {
              if (bazs_.isEmpty()) {
                bazs_ = other.bazs_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureBazsIsMutable();
                bazs_.addAll(other.bazs_);
              }
              onChanged();
            }
          } else {
            if (!other.bazs_.isEmpty()) {
              if (bazsBuilder_.isEmpty()) {
                bazsBuilder_.dispose();
                bazsBuilder_ = null;
                bazs_ = other.bazs_;
                bitField0_ = (bitField0_ & ~0x00000001);
                bazsBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getBazsFieldBuilder() : null;
              } else {
                bazsBuilder_.addAllMessages(other.bazs_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.samn.Test.Foo.Bar parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.samn.Test.Foo.Bar) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated .Test.Foo.Bar.Baz bazs = 1;
        private java.util.List<com.samn.Test.Foo.Bar.Baz> bazs_ =
          java.util.Collections.emptyList();
        private void ensureBazsIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            bazs_ = new java.util.ArrayList<com.samn.Test.Foo.Bar.Baz>(bazs_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            com.samn.Test.Foo.Bar.Baz, com.samn.Test.Foo.Bar.Baz.Builder, com.samn.Test.Foo.Bar.BazOrBuilder> bazsBuilder_;

        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public java.util.List<com.samn.Test.Foo.Bar.Baz> getBazsList() {
          if (bazsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(bazs_);
          } else {
            return bazsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public int getBazsCount() {
          if (bazsBuilder_ == null) {
            return bazs_.size();
          } else {
            return bazsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public com.samn.Test.Foo.Bar.Baz getBazs(int index) {
          if (bazsBuilder_ == null) {
            return bazs_.get(index);
          } else {
            return bazsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder setBazs(
            int index, com.samn.Test.Foo.Bar.Baz value) {
          if (bazsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBazsIsMutable();
            bazs_.set(index, value);
            onChanged();
          } else {
            bazsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder setBazs(
            int index, com.samn.Test.Foo.Bar.Baz.Builder builderForValue) {
          if (bazsBuilder_ == null) {
            ensureBazsIsMutable();
            bazs_.set(index, builderForValue.build());
            onChanged();
          } else {
            bazsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder addBazs(com.samn.Test.Foo.Bar.Baz value) {
          if (bazsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBazsIsMutable();
            bazs_.add(value);
            onChanged();
          } else {
            bazsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder addBazs(
            int index, com.samn.Test.Foo.Bar.Baz value) {
          if (bazsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBazsIsMutable();
            bazs_.add(index, value);
            onChanged();
          } else {
            bazsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder addBazs(
            com.samn.Test.Foo.Bar.Baz.Builder builderForValue) {
          if (bazsBuilder_ == null) {
            ensureBazsIsMutable();
            bazs_.add(builderForValue.build());
            onChanged();
          } else {
            bazsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder addBazs(
            int index, com.samn.Test.Foo.Bar.Baz.Builder builderForValue) {
          if (bazsBuilder_ == null) {
            ensureBazsIsMutable();
            bazs_.add(index, builderForValue.build());
            onChanged();
          } else {
            bazsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder addAllBazs(
            java.lang.Iterable<? extends com.samn.Test.Foo.Bar.Baz> values) {
          if (bazsBuilder_ == null) {
            ensureBazsIsMutable();
            super.addAll(values, bazs_);
            onChanged();
          } else {
            bazsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder clearBazs() {
          if (bazsBuilder_ == null) {
            bazs_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            bazsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public Builder removeBazs(int index) {
          if (bazsBuilder_ == null) {
            ensureBazsIsMutable();
            bazs_.remove(index);
            onChanged();
          } else {
            bazsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public com.samn.Test.Foo.Bar.Baz.Builder getBazsBuilder(
            int index) {
          return getBazsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public com.samn.Test.Foo.Bar.BazOrBuilder getBazsOrBuilder(
            int index) {
          if (bazsBuilder_ == null) {
            return bazs_.get(index);  } else {
            return bazsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public java.util.List<? extends com.samn.Test.Foo.Bar.BazOrBuilder> 
             getBazsOrBuilderList() {
          if (bazsBuilder_ != null) {
            return bazsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(bazs_);
          }
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public com.samn.Test.Foo.Bar.Baz.Builder addBazsBuilder() {
          return getBazsFieldBuilder().addBuilder(
              com.samn.Test.Foo.Bar.Baz.getDefaultInstance());
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public com.samn.Test.Foo.Bar.Baz.Builder addBazsBuilder(
            int index) {
          return getBazsFieldBuilder().addBuilder(
              index, com.samn.Test.Foo.Bar.Baz.getDefaultInstance());
        }
        /**
         * <code>repeated .Test.Foo.Bar.Baz bazs = 1;</code>
         */
        public java.util.List<com.samn.Test.Foo.Bar.Baz.Builder> 
             getBazsBuilderList() {
          return getBazsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            com.samn.Test.Foo.Bar.Baz, com.samn.Test.Foo.Bar.Baz.Builder, com.samn.Test.Foo.Bar.BazOrBuilder> 
            getBazsFieldBuilder() {
          if (bazsBuilder_ == null) {
            bazsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                com.samn.Test.Foo.Bar.Baz, com.samn.Test.Foo.Bar.Baz.Builder, com.samn.Test.Foo.Bar.BazOrBuilder>(
                    bazs_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            bazs_ = null;
          }
          return bazsBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:Test.Foo.Bar)
      }

      static {
        defaultInstance = new Bar(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Test.Foo.Bar)
    }

    private int bitField0_;
    // required string sattr = 1;
    public static final int SATTR_FIELD_NUMBER = 1;
    private java.lang.Object sattr_;
    /**
     * <code>required string sattr = 1;</code>
     */
    public boolean hasSattr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sattr = 1;</code>
     */
    public java.lang.String getSattr() {
      java.lang.Object ref = sattr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sattr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sattr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSattrBytes() {
      java.lang.Object ref = sattr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sattr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 iattr = 2;
    public static final int IATTR_FIELD_NUMBER = 2;
    private long iattr_;
    /**
     * <code>optional uint64 iattr = 2;</code>
     */
    public boolean hasIattr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 iattr = 2;</code>
     */
    public long getIattr() {
      return iattr_;
    }

    // repeated uint32 iiattr = 3;
    public static final int IIATTR_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> iiattr_;
    /**
     * <code>repeated uint32 iiattr = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getIiattrList() {
      return iiattr_;
    }
    /**
     * <code>repeated uint32 iiattr = 3;</code>
     */
    public int getIiattrCount() {
      return iiattr_.size();
    }
    /**
     * <code>repeated uint32 iiattr = 3;</code>
     */
    public int getIiattr(int index) {
      return iiattr_.get(index);
    }

    // optional .Test.Foo.Bar bar = 4;
    public static final int BAR_FIELD_NUMBER = 4;
    private com.samn.Test.Foo.Bar bar_;
    /**
     * <code>optional .Test.Foo.Bar bar = 4;</code>
     */
    public boolean hasBar() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Test.Foo.Bar bar = 4;</code>
     */
    public com.samn.Test.Foo.Bar getBar() {
      return bar_;
    }
    /**
     * <code>optional .Test.Foo.Bar bar = 4;</code>
     */
    public com.samn.Test.Foo.BarOrBuilder getBarOrBuilder() {
      return bar_;
    }

    private void initFields() {
      sattr_ = "";
      iattr_ = 0L;
      iiattr_ = java.util.Collections.emptyList();
      bar_ = com.samn.Test.Foo.Bar.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSattr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSattrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, iattr_);
      }
      for (int i = 0; i < iiattr_.size(); i++) {
        output.writeUInt32(3, iiattr_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, bar_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSattrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, iattr_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < iiattr_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(iiattr_.get(i));
        }
        size += dataSize;
        size += 1 * getIiattrList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, bar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.samn.Test.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.samn.Test.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.samn.Test.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.samn.Test.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.samn.Test.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.samn.Test.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.samn.Test.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.samn.Test.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.samn.Test.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.samn.Test.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.samn.Test.Foo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Test.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.samn.Test.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.samn.Test.internal_static_Test_Foo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.samn.Test.internal_static_Test_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.samn.Test.Foo.class, com.samn.Test.Foo.Builder.class);
      }

      // Construct using com.samn.Test.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBarFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sattr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        iattr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        iiattr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (barBuilder_ == null) {
          bar_ = com.samn.Test.Foo.Bar.getDefaultInstance();
        } else {
          barBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.samn.Test.internal_static_Test_Foo_descriptor;
      }

      public com.samn.Test.Foo getDefaultInstanceForType() {
        return com.samn.Test.Foo.getDefaultInstance();
      }

      public com.samn.Test.Foo build() {
        com.samn.Test.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.samn.Test.Foo buildPartial() {
        com.samn.Test.Foo result = new com.samn.Test.Foo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sattr_ = sattr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.iattr_ = iattr_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          iiattr_ = java.util.Collections.unmodifiableList(iiattr_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.iiattr_ = iiattr_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (barBuilder_ == null) {
          result.bar_ = bar_;
        } else {
          result.bar_ = barBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.samn.Test.Foo) {
          return mergeFrom((com.samn.Test.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.samn.Test.Foo other) {
        if (other == com.samn.Test.Foo.getDefaultInstance()) return this;
        if (other.hasSattr()) {
          bitField0_ |= 0x00000001;
          sattr_ = other.sattr_;
          onChanged();
        }
        if (other.hasIattr()) {
          setIattr(other.getIattr());
        }
        if (!other.iiattr_.isEmpty()) {
          if (iiattr_.isEmpty()) {
            iiattr_ = other.iiattr_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIiattrIsMutable();
            iiattr_.addAll(other.iiattr_);
          }
          onChanged();
        }
        if (other.hasBar()) {
          mergeBar(other.getBar());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSattr()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.samn.Test.Foo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.samn.Test.Foo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string sattr = 1;
      private java.lang.Object sattr_ = "";
      /**
       * <code>required string sattr = 1;</code>
       */
      public boolean hasSattr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sattr = 1;</code>
       */
      public java.lang.String getSattr() {
        java.lang.Object ref = sattr_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sattr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sattr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSattrBytes() {
        java.lang.Object ref = sattr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sattr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sattr = 1;</code>
       */
      public Builder setSattr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sattr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sattr = 1;</code>
       */
      public Builder clearSattr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sattr_ = getDefaultInstance().getSattr();
        onChanged();
        return this;
      }
      /**
       * <code>required string sattr = 1;</code>
       */
      public Builder setSattrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sattr_ = value;
        onChanged();
        return this;
      }

      // optional uint64 iattr = 2;
      private long iattr_ ;
      /**
       * <code>optional uint64 iattr = 2;</code>
       */
      public boolean hasIattr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 iattr = 2;</code>
       */
      public long getIattr() {
        return iattr_;
      }
      /**
       * <code>optional uint64 iattr = 2;</code>
       */
      public Builder setIattr(long value) {
        bitField0_ |= 0x00000002;
        iattr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 iattr = 2;</code>
       */
      public Builder clearIattr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iattr_ = 0L;
        onChanged();
        return this;
      }

      // repeated uint32 iiattr = 3;
      private java.util.List<java.lang.Integer> iiattr_ = java.util.Collections.emptyList();
      private void ensureIiattrIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          iiattr_ = new java.util.ArrayList<java.lang.Integer>(iiattr_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getIiattrList() {
        return java.util.Collections.unmodifiableList(iiattr_);
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public int getIiattrCount() {
        return iiattr_.size();
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public int getIiattr(int index) {
        return iiattr_.get(index);
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public Builder setIiattr(
          int index, int value) {
        ensureIiattrIsMutable();
        iiattr_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public Builder addIiattr(int value) {
        ensureIiattrIsMutable();
        iiattr_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public Builder addAllIiattr(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIiattrIsMutable();
        super.addAll(values, iiattr_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 iiattr = 3;</code>
       */
      public Builder clearIiattr() {
        iiattr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // optional .Test.Foo.Bar bar = 4;
      private com.samn.Test.Foo.Bar bar_ = com.samn.Test.Foo.Bar.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.samn.Test.Foo.Bar, com.samn.Test.Foo.Bar.Builder, com.samn.Test.Foo.BarOrBuilder> barBuilder_;
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public boolean hasBar() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public com.samn.Test.Foo.Bar getBar() {
        if (barBuilder_ == null) {
          return bar_;
        } else {
          return barBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public Builder setBar(com.samn.Test.Foo.Bar value) {
        if (barBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bar_ = value;
          onChanged();
        } else {
          barBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public Builder setBar(
          com.samn.Test.Foo.Bar.Builder builderForValue) {
        if (barBuilder_ == null) {
          bar_ = builderForValue.build();
          onChanged();
        } else {
          barBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public Builder mergeBar(com.samn.Test.Foo.Bar value) {
        if (barBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              bar_ != com.samn.Test.Foo.Bar.getDefaultInstance()) {
            bar_ =
              com.samn.Test.Foo.Bar.newBuilder(bar_).mergeFrom(value).buildPartial();
          } else {
            bar_ = value;
          }
          onChanged();
        } else {
          barBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public Builder clearBar() {
        if (barBuilder_ == null) {
          bar_ = com.samn.Test.Foo.Bar.getDefaultInstance();
          onChanged();
        } else {
          barBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public com.samn.Test.Foo.Bar.Builder getBarBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBarFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      public com.samn.Test.Foo.BarOrBuilder getBarOrBuilder() {
        if (barBuilder_ != null) {
          return barBuilder_.getMessageOrBuilder();
        } else {
          return bar_;
        }
      }
      /**
       * <code>optional .Test.Foo.Bar bar = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.samn.Test.Foo.Bar, com.samn.Test.Foo.Bar.Builder, com.samn.Test.Foo.BarOrBuilder> 
          getBarFieldBuilder() {
        if (barBuilder_ == null) {
          barBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.samn.Test.Foo.Bar, com.samn.Test.Foo.Bar.Builder, com.samn.Test.Foo.BarOrBuilder>(
                  bar_,
                  getParentForChildren(),
                  isClean());
          bar_ = null;
        }
        return barBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Test.Foo)
    }

    static {
      defaultInstance = new Foo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Test.Foo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_Foo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Test_Foo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_Foo_Bar_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Test_Foo_Bar_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_Foo_Bar_Baz_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Test_Foo_Bar_Baz_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037test/resources/proto/test.proto\022\004Test\"" +
      "\213\001\n\003Foo\022\r\n\005sattr\030\001 \002(\t\022\r\n\005iattr\030\002 \001(\004\022\016\n" +
      "\006iiattr\030\003 \003(\r\022\032\n\003bar\030\004 \001(\0132\r.Test.Foo.Ba" +
      "r\032:\n\003Bar\022\037\n\004bazs\030\001 \003(\0132\021.Test.Foo.Bar.Ba" +
      "z\032\022\n\003Baz\022\013\n\003baz\030\001 \001(\tB\n\n\010com.samn"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Test_Foo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Test_Foo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Test_Foo_descriptor,
              new java.lang.String[] { "Sattr", "Iattr", "Iiattr", "Bar", });
          internal_static_Test_Foo_Bar_descriptor =
            internal_static_Test_Foo_descriptor.getNestedTypes().get(0);
          internal_static_Test_Foo_Bar_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Test_Foo_Bar_descriptor,
              new java.lang.String[] { "Bazs", });
          internal_static_Test_Foo_Bar_Baz_descriptor =
            internal_static_Test_Foo_Bar_descriptor.getNestedTypes().get(0);
          internal_static_Test_Foo_Bar_Baz_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Test_Foo_Bar_Baz_descriptor,
              new java.lang.String[] { "Baz", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
